// This allows TypeScript to pick up the magic constants that's auto-generated by Forge's Vite
// plugin that tells the Electron app where to look for the Vite-bundled app code (depending on
// whether you're running in development or production).
declare const MAIN_WINDOW_VITE_DEV_SERVER_URL: string;
declare const MAIN_WINDOW_VITE_NAME: string;

export interface IElectronAPI {
  openGitHub: () => void;
}
export interface IStoreAPI {
  get: <T>(key: string, defaultValue: T) => Promise<T>;
  set: <T>(key: string, value: T) => Promise<void>;
}

export interface ISourceFileAPI {
  saveFile: (content: string) => Promise<void>;
  readFile: () => Promise<string>;
  onSaveShortcut: (fn: () => void) => string;
}

declare global {
  interface Window {
    electronAPI: IElectronAPI;
    storeAPI: IStoreAPI;
    sourceFileAPI: ISourceFileAPI;
  }
}
